name: Generate Blog View

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Generate Blog View
      run: |
        python scripts/generate_blog.py --days 5 --output blog-view.md
    
    - name: Commit and Push if changed
      run: |
        git config --local user.email "anikethprajapati@gmail.com"
        git config --local user.name "Aniket P"
        git add blog-view.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: Generate blog view [skip ci]" && git push)